<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Dylan Hult — Digital Marketing & Social Media</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,500;12..96,700&family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css">
</head><body>
<header><a class="logo" href="#home">DHLT<span>.</span></a><nav><a href="#work">Work</a><a href="#about">About</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav><a class="header-cta" href="#contact">Let's talk ↗</a></header>

<section id="home" class="hero">
  <div class="hero-copy">
    <div class="micro">DYLAN HULT / DIGITAL MARKETING + SOCIAL MEDIA</div>
    <h1>Content that<br><em>gets attention.</em><br>Strategy that<br><em>moves numbers.</em></h1>
    <p>I build social content, manage platforms, study audiences, and turn performance data into the next creative move.</p>
    <div class="hero-actions"><a href="#work">See the work ↓</a><a href="#contact">Let's talk ↗</a></div>
  </div>
  <div class="hero-visual">
    <div class="portrait"><img src="https://static.wixstatic.com/media/a8d4fc_c5d43194b3a64fb4aefef69a65ecbd87~mv2.jpg/v1/crop/x_0%2Cy_68%2Cw_1080%2Ch_1080/fill/w_900%2Ch_900%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/IMG_5948_edited_edited_edited_edited.jpg" alt="Dylan Hult"><div class="portrait-tag">BA ADVERTISING<br>BGSU / 2026</div></div>
    <div class="floating-proof"><span>REAL WORK / REAL RESULTS</span><b>13K</b><small>FOLLOWERS BUILT</small><b>12M+</b><small>VIDEO VIEWS</small><b>30+</b><small>APPOINTMENTS</small></div>
  </div>
  <div class="hero-foot"><span>CHICAGO AREA</span><span>CONTENT / STRATEGY / ANALYTICS</span><span>SCROLL ↓</span></div>
</section>
<section class="track">
<div class="track-label">PROOF / FIRST IMPRESSION</div>
<div class="track-grid">
<div><b>0 → 13K</b><span>CLIPPERR__ FOLLOWERS</span></div>
<div><b>12M+</b><span>CLIPPERR__ VIDEO VIEWS</span></div>
<div><b>+370%</b><span>SONDER TIKTOK FOLLOWERS</span></div>
<div><b>30+</b><span>SONDER APPOINTMENTS</span></div>
</div>
<div class="proof-note"><span>WHAT I DO</span><strong>Social media management · short-form content · audience research · campaign strategy · analytics · creative production</strong></div>
</section>
<section id="work" class="work">
<div class="section-line"><span>02 / WORK</span><span>PROOF BEFORE PARAGRAPHS</span></div>
<div class="work-head"><h2>Selected<br><em>work.</em></h2><p>Professional experience, independent projects, and academic work. Real work. Real links. Real numbers.</p></div>

<article class="hero-project sonder"><div class="project-text"><span>01 / PROFESSIONAL EXPERIENCE</span><h3>SONDER<br><em>SPA</em></h3><p>Social strategy, short-form content, audience targeting and performance optimization across Instagram and TikTok.</p><div class="stats"><b>30+<small>APPOINTMENTS</small></b><b>67.6K<small>TIKTOK VIEWS</small></b><b>+370%<small>TIKTOK FOLLOWERS</small></b></div><a href="#sonder">View case study ↗</a></div>
<div class="visual sonder-visual"><div class="phone p1"><div class="phone-top">INSTAGRAM</div><div class="screen s1"></div><strong>22.2K</strong><small>ORGANIC VIEWS</small></div><div class="phone p2"><div class="phone-top">TIKTOK</div><div class="screen s2"></div><strong>67.6K</strong><small>ORGANIC VIEWS</small></div><div class="visual-note">SOCIAL<br>MEDIA<br>STRATEGY</div></div></article>

<article class="hero-project clip"><div class="visual clip-visual"><div class="browser"><div class="browser-top"><i></i><i></i><i></i><span>@clipperr__ / analytics</span></div><div class="browser-body"><img src="https://static.wixstatic.com/media/a8d4fc_8805c52f32e34c5e98c82333b7232be0~mv2.png/v1/fill/w_600%2Ch_260%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/Screen%20Shot%202026-09-03%20at%205_19_58%20PM.png" alt="Clipperr profile screenshot"><div><b>13K</b><small>FOLLOWERS</small><b>12M+</b><small>VIEWS</small></div></div></div><div class="clip-sticker">1.1M<br><small>TOP VIDEO</small></div></div><div class="project-text"><span>02 / INDEPENDENT PROJECT</span><h3>CLIPPERR<span>__</span></h3><p>Built and managed a short-form TikTok account from zero through content selection, editing, captions, publishing and analytics.</p><div class="stats"><b>13K<small>FOLLOWERS</small></b><b>12M+<small>VIEWS</small></b><b>25<small>100K+ VIDEOS</small></b></div><a href="#clipper">View case study ↗</a></div></article>

<article class="hero-project brez"><div class="project-text"><span>03 / INDEPENDENT PROJECT</span><h3>BREZ<br><em>SCALES</em></h3><p>A creator-focused theme page built through clipping, testing, publishing and performance-led content decisions.</p><div class="stats"><b>1.9K<small>FOLLOWERS</small></b><b>1.6M+<small>VIEWS</small></b><b>1.5M<small>TOP VIDEO</small></b></div><a href="#brez">View case study ↗</a></div><div class="visual brez-visual"><img src="https://static.wixstatic.com/media/a8d4fc_64622672dd5a46d2a50dd41299d82f48~mv2.png/v1/fill/w_600%2Ch_284%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/Screen%20Shot%202026-08-01%20at%202_48_19%20AM.png" alt="Brez Scales profile screenshot"><div class="brez-sticker">1.5M<br><small>TOP VIDEO</small></div></div></article>

<div class="more">
<div class="section-line"><span>04—08 / MORE WORK</span><span>ACADEMIC + PROFESSIONAL</span></div>
<a href="#ulta"><span>04</span><b>Ulta Beauty</b><small>Integrated advertising campaign</small><i>↗</i></a>
<a href="#nba"><span>05</span><b>Las Vegas NBA Expansion</b><small>Market research + integrated promotion</small><i>↗</i></a>
<a href="#research"><span>06</span><b>Audience Research</b><small>Dynata + Falcon Media research</small><i>↗</i></a>
<a href="#other"><span>07</span><b>Additional Creative Work</b><small>Chicago Bulls PR · Apple · Gaming Console · Promotions</small><i>↗</i></a>
<a href="#bgsu"><span>08</span><b>BGSU School of Media & Communication</b><small>Social Media Promotion Intern</small><i>↗</i></a>
</div>
</section>

<section class="academic-preview">
<div class="section-line"><span>ACADEMIC / SELECTED PROOF</span><span>ADVERTISING · RESEARCH · PR · STRATEGY</span></div>
<div class="academic-intro"><h2>The rest of<br><em>the work.</em></h2><p>Campaigns, audience research, brand analysis, PR and media projects from BGSU, shown through the actual work instead of a wall of descriptions.</p></div>
<div class="academic-strip">
<a href="#ulta"><span>01</span><b>ULTA BEAUTY</b><small>Integrated campaign</small></a>
<a href="#nba"><span>02</span><b>LAS VEGAS NBA</b><small>Research + promotion</small></a>
<a href="#research"><span>03</span><b>DYNATA</b><small>Audience research</small></a>
<a href="#other"><span>04</span><b>APPLE / BULLS / GAMING</b><small>Brand + PR + visual media</small></a>
</div>
</section>

<section id="about" class="about"><div class="section-line"><span>03 / ABOUT</span><span>PERSONAL / PRACTICAL / CURIOUS</span></div><div class="about-grid"><div><div class="about-word">DYLAN</div><h2>Strategy<br>with a<br><em>creative edge.</em></h2></div><div class="about-copy"><p class="lead">I’m a recent BGSU advertising graduate with a minor in Media Production.</p><p>My work sits between creative and performance: making short-form content, understanding audiences, building campaigns, and looking at the numbers to figure out what should happen next.</p><p>I’ve worked across professional internships, independent creator projects, and academic campaigns, research and public relations projects.</p><div class="skills"><span>Social Media</span><span>Content Strategy</span><span>Short-Form Video</span><span>Audience Research</span><span>Campaign Planning</span><span>Analytics</span><span>Digital Marketing</span><span>Video Editing</span></div></div></div></section>

<section id="experience" class="experience"><div class="section-line"><span>04 / EXPERIENCE</span><span>WHERE I PUT IT TO WORK</span></div><div class="jobs">
<div><small>DEC 2025 — APR 2026</small><h3>Sonder Spa</h3><p>Social Media Intern</p><b>PROFESSIONAL</b></div>
<div><small>2024 — PRESENT</small><h3>Clipperr__</h3><p>Independent Content Creator & Account Manager</p><b>INDEPENDENT</b></div>
<div><small>FEB 2025 — APR 2025</small><h3>BGSU School of Media & Communication</h3><p>Social Media Promotion Intern</p><b>PROFESSIONAL</b></div>
<div><small>MAY 2026</small><h3>Bowling Green State University</h3><p>B.A. Advertising · Minor in Media Production</p><b>EDUCATION</b></div></div></section>

<section id="contact" class="contact"><div class="section-line"><span>05 / CONTACT</span><span>OPEN TO OPPORTUNITIES</span></div><h2>Let's make<br>something <em>move.</em></h2><a class="email" href="mailto:dhult1026@gmail.com">dhult1026@gmail.com ↗</a><div class="contact-foot"><span>DYLAN HULT</span><span>+1 (708) 941-6844</span><span>CHICAGO AREA</span></div></section>

<!-- Case studies -->
<section id="sonder" class="overlay"><div class="overlay-inner"><a href="#work" class="close">CLOSE ×</a><span>PROFESSIONAL EXPERIENCE / SONDER SPA</span><h2>Sonder <em>Spa.</em></h2><div class="case-metrics"><b>30+<small>appointments</small></b><b>67.6K<small>TikTok views</small></b><b>5.8K<small>TikTok interactions</small></b><b>22.2K<small>Instagram views</small></b></div><div class="case-copy"><p>Managed Instagram and TikTok, posted four times per week on each platform, created and edited content, engaged with the audience, and adjusted strategy based on performance.</p><h4>TOP TIKTOK POSTS</h4><a class="media-link" href="https://www.tiktok.com/@sonderspa419/video/7617990971426606350?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Post 1</span><b>8.1K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@sonderspa419/video/7630527845281828126?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Post 2</span><b>7.7K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@sonderspa419/video/7617608968415841550?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Post 3</span><b>5.2K views</b><i>↗</i></a><h4>TOP INSTAGRAM REELS</h4><a class="media-link" href="https://www.instagram.com/reel/DSYazjBkfco/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==" target="_blank" rel="noopener"><span>Post 1</span><b>1.3K views</b><i>↗</i></a><a class="media-link" href="https://www.instagram.com/reel/DT_khJ8DOzm/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==" target="_blank" rel="noopener"><span>Post 2</span><b>1.0K views</b><i>↗</i></a><a class="media-link" href="https://www.instagram.com/reel/DV4N2pBERKd/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==" target="_blank" rel="noopener"><span>Post 3</span><b>827 views</b><i>↗</i></a><h4>PROJECT ASSETS</h4><div class="asset-note">The original Wix portfolio also contains the uploaded video files and screenshots for these posts. The public TikTok/Instagram links above are restored here; the private Wix-hosted video files themselves are not exposed in the public page source.</div></div></div></section>

<section id="clipper" class="overlay"><div class="overlay-inner"><a href="#work" class="close">CLOSE ×</a><span>INDEPENDENT PROJECT / @CLIPPERR__</span><h2>Clipperr<span>__</span></h2><div class="case-metrics"><b>13K<small>followers</small></b><b>12M+<small>views</small></b><b>1.1M+<small>likes</small></b><b>180<small>videos</small></b></div><img class="profile-shot" src="https://static.wixstatic.com/media/a8d4fc_8805c52f32e34c5e98c82333b7232be0~mv2.png/v1/fill/w_600%2Ch_260%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/Screen%20Shot%202026-09-03%20at%205_19_58%20PM.png" alt="Clipperr profile screenshot"><div class="case-copy"><p>Built and managed a personal TikTok account focused on high-engagement moments from streamers, YouTubers and online personalities. Responsible for selection, editing, captions, publishing, analytics and growth strategy.</p><h4>500K+ VIEW VIDEOS</h4><a class="media-link" href="https://www.tiktok.com/@clipperr__/video/7449603748294429983?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Top video</span><b>1.1M views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@clipperr__/video/7490650649873501470?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Video 2</span><b>685K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@clipperr__/video/7491158155125132574?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Video 3</span><b>518K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@clipperr__/video/7450616020676480286?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Video 4</span><b>670K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@clipperr__/video/7495531525618945310?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Video 5</span><b>925K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@clipperr__/video/7545289944521116941?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Video 6</span><b>562K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@clipperr__/video/7659852241901194526?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Video 7</span><b>546K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@clipperr__/video/7583607354382355743?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Video 8</span><b>831.6K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@clipperr__/video/7660235512908762399?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Video 9</span><b>530K views</b><i>↗</i></a><h4>PROFILE / PERFORMANCE</h4><p>25 videos exceeded 100K views and 9 exceeded 500K views. The top video reached 1.1M views. The account also qualified for and joined TikTok's Creator Rewards Program.</p></div></div></section>

<section id="brez" class="overlay"><div class="overlay-inner"><a href="#work" class="close">CLOSE ×</a><span>INDEPENDENT PROJECT / @BREZ.SCALES.CLIPS</span><h2>Brez <em>Scales.</em></h2><div class="case-metrics"><b>1.9K<small>followers</small></b><b>1.6M+<small>views</small></b><b>106.3K<small>likes</small></b><b>1.5M<small>top video</small></b></div><img class="profile-shot" src="https://static.wixstatic.com/media/a8d4fc_64622672dd5a46d2a50dd41299d82f48~mv2.png/v1/fill/w_600%2Ch_284%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/Screen%20Shot%202026-08-01%20at%202_48_19%20AM.png" alt="Brez Scales profile screenshot"><div class="case-copy"><p>Created and managed a TikTok theme page through content selection, editing, captions, posting, analytics and growth strategy as part of a Whop clipping campaign.</p><h4>TOP 5 PERFORMING VIDEOS</h4><a class="media-link" href="https://www.tiktok.com/@brez.scales.clips/video/7495488430680411422?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Top 1</span><b>1.5M views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@brez.scales.clips/video/7490641911099804958?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Top 2</span><b>28.9K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@brez.scales.clips/video/7492518930649468190?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Top 3</span><b>12.5K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@brez.scales.clips/video/7495129016614145310?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Top 4</span><b>12.1K views</b><i>↗</i></a><a class="media-link" href="https://www.tiktok.com/@brez.scales.clips/video/7497012088494165278?is_from_webapp=1&sender_device=pc" target="_blank" rel="noopener"><span>Top 5</span><b>11.6K views</b><i>↗</i></a><h4>WHAT THE DATA SHOWED</h4><p>Luxury lifestyle content consistently outperformed standard informational content, while talking-head videos generally underperformed due to lower retention and visual stimulation.</p></div></div></section>

<section id="ulta" class="overlay"><div class="overlay-inner"><a href="#work" class="close">CLOSE ×</a><span>ACADEMIC PROJECT / ADV 4800</span><h2>Ulta <em>Beauty.</em></h2><div class="case-copy"><p>Served as research lead on a four-person team developing an integrated advertising campaign for Ulta Beauty. Work included SWOT analysis, focus group synthesis, audience insights, campaign strategy and media recommendations.</p><a class="doc" href="https://20f88086-2a6a-4877-9c65-7aefd2e671eb.filesusr.com/ugd/a8d4fc_8540fedad7204302a796ebdf2c86ca2f.pdf" target="_blank">View project PDF ↗</a><div class="gallery"><img src="https://static.wixstatic.com/media/a8d4fc_956f9ccdca4649cc86b009276ee0cae1~mv2.png/v1/fill/w_980%2Ch_551%2Cal_c%2Cq_90%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/a8d4fc_956f9ccdca4649cc86b009276ee0cae1~mv2.png" alt="Ulta project screenshot"><img src="https://static.wixstatic.com/media/a8d4fc_ba4fa97c7d59412ba1a7b96e7d77b805~mv2.png/v1/fill/w_980%2Ch_581%2Cal_c%2Cq_90%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/a8d4fc_ba4fa97c7d59412ba1a7b96e7d77b805~mv2.png" alt="Ulta project screenshot"></div></div></div></section>

<section id="nba" class="overlay"><div class="overlay-inner"><a href="#work" class="close">CLOSE ×</a><span>ACADEMIC PROJECT / ADV 3800</span><h2>Las Vegas NBA <em>Expansion.</em></h2><div class="case-copy"><p>Conducted market research and developed an integrated promotional campaign for launching a hypothetical NBA expansion team in Las Vegas, including demographic analysis, SWOT evaluation, email strategy, social media planning and creative development.</p><div class="gallery"><img src="https://static.wixstatic.com/media/a8d4fc_08bdaf32da624d64b6cbb9a459b65104~mv2.png/v1/fill/w_980%2Ch_583%2Cal_c%2Cq_90%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/a8d4fc_08bdaf32da624d64b6cbb9a459b65104~mv2.png" alt="Academic project screenshot"><img src="https://static.wixstatic.com/media/a8d4fc_d97ea239582d47f7880341ac2eb1f355~mv2.png/v1/fill/w_980%2Ch_559%2Cal_c%2Cq_90%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/a8d4fc_d97ea239582d47f7880341ac2eb1f355~mv2.png" alt="Academic project screenshot"></div></div></div></section>

<section id="research" class="overlay"><div class="overlay-inner"><a href="#work" class="close">CLOSE ×</a><span>ACADEMIC PROJECT / RESEARCH</span><h2>Audience <em>Research.</em></h2><div class="case-copy"><p>Research work across Falcon Media/WBGU and Dynata, using surveys, interviews and analytics to identify awareness, engagement patterns, audience needs and opportunities for improvement.</p><a class="doc" href="https://20f88086-2a6a-4877-9c65-7aefd2e671eb.filesusr.com/ugd/a8d4fc_8540fedad7204302a796ebdf2c86ca2f.pdf" target="_blank">View project PDF ↗</a><div class="gallery"><img src="https://static.wixstatic.com/media/a8d4fc_293795d360b84fddbfcfeb1926874825~mv2.png/v1/fill/w_980%2Ch_547%2Cal_c%2Cq_90%2Cusm_0.66_1.00_0.01%2Cenc_avif%2Cquality_auto/a8d4fc_293795d360b84fddbfcfeb1926874825~mv2.png" alt="Research project screenshot"></div></div></div></section>

<section id="bgsu" class="overlay"><div class="overlay-inner"><a href="#work" class="close">CLOSE ×</a><span>PROFESSIONAL EXPERIENCE / BGSU SMC</span><h2>BGSU School of <em>Media & Communication.</em></h2><div class="case-copy"><p><b>Social Media Promotion Intern · Feb 2025 — Apr 2025</b></p><p>Created promotional content across social media, email marketing, campus slides and digital communications supporting academic programs, events, scholarships and student achievements.</p><p>Worked with three student interns and a faculty supervisor, participated in weekly analytics/strategy meetings, and managed planning, drafting, revision and delivery of content.</p><img class="bgsu-shot" src="https://static.wixstatic.com/media/a8d4fc_146524c30319464aa391e2803bcbfb92~mv2.jpg/v1/fill/w_305%2Ch_306%2Cal_c%2Clg_1%2Cq_80%2Cenc_avif%2Cquality_auto/Screen%20Shot%202026-08-05%20at%2010_edited.jpg" alt="BGSU internship screenshot"><h4>WORK INCLUDED</h4><p>Course promotion · scholarship promotion · study-abroad promotion · student success stories · social posts · email campaigns · digital flyers · analytics-driven strategy</p></div></div></section>

<section id="other" class="overlay"><div class="overlay-inner"><a href="#work" class="close">CLOSE ×</a><span>ADDITIONAL WORK</span><h2>More <em>work.</em></h2><div class="other-grid"><div><b>Chicago Bulls PR Campaign</b><span>PR 4420 · Sports Public Relations</span></div><div><b>Apple Brand Report</b><span>ADV 3400 · Brand Storytelling</span></div><div><b>Gaming Console</b><span>VCT 1030 · Visual Communication Technology</span></div><div><b>Paris Study Abroad Promotion</b><span>Solo media creation</span></div><div><b>MDIA 2500 Class Promotion</b><span>Promotional content</span></div><div><b>Scholarship Opportunity Post</b><span>Promotional content</span></div><div><b>Fall 2025 JOUR Courses Email</b><span>Email marketing</span></div></div></div></section>

<footer><span>DHLT / DYLAN HULT</span><span>Digital Marketing · Social Media · Content</span><span>© 2026</span></footer>
<script src="script.js"></script></body></html>